/*
 * Copyright 2025 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.perftests.itsass.simSteps

import io.gatling.core.action.builder.PauseBuilder
import io.gatling.core.session.ExpressionSuccessWrapper
import uk.gov.hmrc.performance.simulation._
import uk.gov.hmrc.perftests.itsass.requests.AuthLoginRequests.{getLoginPage, postAgentLoginPage, postIndividualLoginPage}
import uk.gov.hmrc.perftests.itsass.requests.DividendsRequests._
import uk.gov.hmrc.perftests.itsass.requests.IncomeTaxSubmissionRequests.{getInsertAdditionalParametersEndPoint, getStartPage, getYourIncomeTaxReturnPage}
import uk.gov.hmrc.perftests.itsass.requests.RequestsHelper.taxYear
import uk.gov.hmrc.perftests.itsass.requests.TailorReturnRequests._

import scala.concurrent.duration.DurationInt

trait TailorReturnSimSteps extends PerformanceTestRunner {

  def pause(millis: Int) = new PauseBuilder(millis.millis.expressionSuccess, None)

  def IndividualTaskList(id: String, description: String): JourneyPart = setup(id, description).withRequests(
    getLoginPage,
    postIndividualLoginPage("AA123459A", "1234567890", taxYear),
    //TODO: The below is a temporary fix; a code change is required to retrieve NINO from Auth for Individuals
    getInsertAdditionalParametersEndPoint("AA123459A", "1234567890", taxYear),
    getStartPage(taxYear),
    getTailorReturnStartPage(taxYear),
    getTailorReturnAddSectionsPage(taxYear),
    getUkResidenceStatusPage(taxYear),
    postUkResidenceStatusPage(taxYear),
    getCharitableDonationsPage(taxYear),
    postCharitableDonationsPage(taxYear),
    getChangeCharitableDonationsPage(taxYear),
    postChangeCharitableDonationsPage(taxYear),
    getMarriageAllowancePage(taxYear),
    postMarriageAllowancePage(taxYear),
    getChangeMarriageAllowancePage(taxYear),
    postChangeMarriageAllowancePage(taxYear),
    getChildBenefitPage(taxYear),
    postChildBenefitPage(taxYear),
    getChildBenefitIncomePage(taxYear),
    postChildBenefitIncomePage(taxYear),
    getChangeChildBenefitIncomePage(taxYear),
    postChangeChildBenefitIncomePage(taxYear),
    getHighIncomeChildBenefitChargePage(taxYear),
    postHighIncomeChildBenefitChargePage(taxYear),
    getFosterCarerPage(taxYear),
    postFosterCarerPage(taxYear),
    getChangeFosterCarerPage(taxYear),
    postChangeFosterCarerPage(taxYear),
    getPatentRoyaltyPaymentsPage(taxYear),
    postPatentRoyaltyPaymentsPage(taxYear),
    getTaxAvoidanceSchemesPage(taxYear),
    postTaxAvoidanceSchemesPage(taxYear),
    getChangeTaxAvoidanceSchemesPage(taxYear),
    postChangeTaxAvoidanceSchemesPage(taxYear),
    getAboutYourWorkPage(taxYear),
    postAboutYourWorkPage(taxYear),
    getChangeAboutYourWorkPage(taxYear),
    postChangeAboutYourWorkPage(taxYear),
    getConstructionIndustrySchemePage(taxYear),
    postConstructionIndustrySchemePage(taxYear),
    getChangeConstructionIndustrySchemePage(taxYear),
    postChangeConstructionIndustrySchemePage(taxYear),
    getJobseekersAllowancePage(taxYear),
    postJobseekersAllowancePage(taxYear),
    getChangeJobseekersAllowancePage(taxYear),
    postChangeJobseekersAllowancePage(taxYear),
    getRentalIncomePage(taxYear),
    postRentalIncomePage(taxYear),
    getChangeRentalIncomePage(taxYear),
    postChangeRentalIncomePage(taxYear),
    getPensionsPage(taxYear),
    postPensionsPage(taxYear),
    getChangePensionsPage(taxYear),
    postChangePensionsPage(taxYear),
    getUKInsuranceGainsPage(taxYear),
    postUKInsuranceGainsPage(taxYear),
    getChangeUKInsuranceGainsPage(taxYear),
    postChangeUKInsuranceGainsPage(taxYear),
    getUKInterestPage(taxYear),
    postUKInterestPage(taxYear),
    getChangeUKInsuranceGainsPage(taxYear),
    postChangeUKInsuranceGainsPage(taxYear),
    getUKDividendsSharesLoansPage(taxYear),
    postUKDividendsSharesLoansPage(taxYear),
    getChangeUKDividendsSharesLoansPage(taxYear),
    postChangeUKDividendsSharesLoansPage(taxYear),
    getPaymentsPensionsPage(taxYear),
    postPaymentsPensionsPage(taxYear),
    getChangePaymentsPensionsPage(taxYear),
    postChangePaymentsPensionsPage(taxYear),
    getTaskListPage(taxYear)
  )

  def AgentTaskList(id: String, description: String): JourneyPart = setup(id, description) withRequests(
    getLoginPage,
    postAgentLoginPage("AA123459A", "1234567890", taxYear),
    getInsertAdditionalParametersEndPoint("AA123459A", "1234567890", taxYear),
    getStartPage(taxYear),
    getTailorReturnStartPage(taxYear),
    getTailorReturnAddSectionsPage(taxYear),
    getUkResidenceStatusPage(taxYear),
    postUkResidenceStatusPage(taxYear),
    getChangeUkResidenceStatusPage(taxYear),
    postChangeUkResidenceStatusPage(taxYear),
    getYourResidenceStatusPage(taxYear),
    postYourResidenceStatusPage(taxYear),
    getChangeYourResidenceStatusPage(taxYear),
    postChangeYourResidenceStatusPage(taxYear),
    getCharitableDonationsPage(taxYear),
    postCharitableDonationsPage(taxYear),
    getChangeCharitableDonationsPage(taxYear),
    postChangeCharitableDonationsPage(taxYear),
    getFosterCarerPage(taxYear),
    postFosterCarerPage(taxYear),
    getChangeFosterCarerPage(taxYear),
    postChangeFosterCarerPage(taxYear),
    getChildBenefitPage(taxYear),
    postChildBenefitPage(taxYear),
    getChangeChildBenefitPage(taxYear),
    postChangeChildBenefitPage(taxYear),
    getChildBenefitIncomePage(taxYear),
    postChildBenefitIncomePage(taxYear),
    getChangeChildBenefitIncomePage(taxYear),
    postChangeChildBenefitIncomePage(taxYear),
    getHighIncomeChildBenefitChargePage(taxYear),
    postHighIncomeChildBenefitChargePage(taxYear),
    getChangeHighIncomeChildBenefitChargePage(taxYear),
    postChangeHighIncomeChildBenefitChargePage(taxYear),
    getMarriageAllowancePage(taxYear),
    postMarriageAllowancePage(taxYear),
    getChangeMarriageAllowancePage(taxYear),
    postChangeMarriageAllowancePage(taxYear),
    getTaxAvoidanceSchemesPage(taxYear),
    postTaxAvoidanceSchemesPage(taxYear),
    getChangeTaxAvoidanceSchemesPage(taxYear),
    postChangeTaxAvoidanceSchemesPage(taxYear),
    getAboutYourWorkPage(taxYear),
    postAboutYourWorkPage(taxYear),
    getChangeAboutYourWorkPage(taxYear),
    postChangeAboutYourWorkPage(taxYear),
    getConstructionIndustrySchemePage(taxYear),
    postConstructionIndustrySchemePage(taxYear),
    getChangeConstructionIndustrySchemePage(taxYear),
    postChangeConstructionIndustrySchemePage(taxYear),
    getJobseekersAllowancePage(taxYear),
    postJobseekersAllowancePage(taxYear),
    getChangeJobseekersAllowancePage(taxYear),
    postChangeJobseekersAllowancePage(taxYear),
    getRentalIncomePage(taxYear),
    postRentalIncomePage(taxYear),
    getChangeRentalIncomePage(taxYear),
    postChangeRentalIncomePage(taxYear),
    getPensionsPage(taxYear),
    postPensionsPage(taxYear),
    getChangePensionsPage(taxYear),
    postChangePensionsPage(taxYear),
    getUKInsuranceGainsPage(taxYear),
    postUKInsuranceGainsPage(taxYear),
    getChangeUKInsuranceGainsPage(taxYear),
    postChangeUKInsuranceGainsPage(taxYear),
    getUKInterestPage(taxYear),
    postUKInterestPage(taxYear),
    postChangeUKInterestPage(taxYear),
    getChangeUKInterestPage(taxYear),
    getUKDividendsSharesLoansPage(taxYear),
    postUKDividendsSharesLoansPage(taxYear),
    getChangeUKDividendsSharesLoansPage(taxYear),
    postChangeUKDividendsSharesLoansPage(taxYear),
    getPaymentsPensionsPage(taxYear),
    postPaymentsPensionsPage(taxYear),
    getChangePaymentsPensionsPage(taxYear),
    postChangePaymentsPensionsPage(taxYear),
    getTaskListPage(taxYear)
  )

  def IndividualDividends(id: String, description: String): JourneyPart = setup(id, description) withRequests(
    getLoginPage,
    postIndividualLoginPage("AA123459A", "1234567890", taxYear),
    //TODO: The below is a temporary fix; a code change is required to retrieve NINO from Auth for Individuals
    getInsertAdditionalParametersEndPoint("AA123459A", "1234567890", taxYear),
    getStartPage(taxYear),
    getTailorReturnStartPage(taxYear),
    getTailorReturnAddSectionsPage(taxYear),
    getUkResidenceStatusPage(taxYear),
    postUkResidenceStatusPage(taxYear),
    getCharitableDonationsPage(taxYear),
    postCharitableDonationsPage(taxYear),
    getMarriageAllowancePage(taxYear),
    postMarriageAllowancePage(taxYear),
    getChildBenefitPage(taxYear),
    postChildBenefitPage(taxYear),
    getChildBenefitIncomePage(taxYear),
    postChildBenefitIncomePage(taxYear),
    getHighIncomeChildBenefitChargePage(taxYear),
    postHighIncomeChildBenefitChargePage(taxYear),
    getFosterCarerPage(taxYear),
    postFosterCarerPage(taxYear),
    getChangeFosterCarerPage(taxYear),
    postChangeFosterCarerPage(taxYear),
    getPatentRoyaltyPaymentsPage(taxYear),
    postPatentRoyaltyPaymentsPage(taxYear),
    getTaxAvoidanceSchemesPage(taxYear),
    postTaxAvoidanceSchemesPage(taxYear),
    getAboutYourWorkPage(taxYear),
    postAboutYourWorkPage(taxYear),
    getJobseekersAllowancePage(taxYear),
    postJobseekersAllowancePage(taxYear),
    getChangeJobseekersAllowancePage(taxYear),
    postChangeJobseekersAllowancePage(taxYear),
    getRentalIncomePage(taxYear),
    postRentalIncomePage(taxYear),
    getPensionsPage(taxYear),
    postPensionsPage(taxYear),
    getUKInsuranceGainsPage(taxYear),
    postUKInsuranceGainsPage(taxYear),
    getUKInterestPage(taxYear),
    postUKInterestPage(taxYear),
    getUKDividendsSharesLoansPage(taxYear),
    postAllDividendsSharesLoansPage(taxYear),
    getPaymentsPensionsPage(taxYear),
    postPaymentsPensionsPage(taxYear),
    getTaskListPage(taxYear),
    getUKDividendsAmountPage(taxYear),
    postUKDividendsAmountPage(taxYear),
    getCheckUKDividendsAmountPage(taxYear),
    postCheckUKDividendsAmountPage(taxYear),
    getStockDividendsAmountPage(taxYear),
    postStockDividendsAmountPage(taxYear),
    getCheckStockDividendsAmountPage(taxYear),
    postCheckStockDividendsAmountPage(taxYear),
    getStockDividendSectionCompletedPage(taxYear),
    postStockDividendSectionCompletedPage(taxYear),
    getOtherDividendsAmountPage(taxYear),
    postOtherDividendsAmountPage(taxYear),
    getRedeemableSharesAmountPage(taxYear),
    postRedeemableSharesAmountPage(taxYear),
    getCheckRedeemableSharesAmountPage(taxYear),
    postCheckRedeemableSharesAmountPage(taxYear),
    getRedeemableSharesSectionCompletedPage(taxYear),
    postRedeemableSharesSectionCompletedPage(taxYear),
    getCloseCompanyLoanAmountPage(taxYear),
    postCloseCompanyLoanAmountPage(taxYear),
    getCheckCloseCompanyLoanAmountPage(taxYear),
    postCheckCloseCompanyLoanAmountPage(taxYear),
    getCloseCompanyLoanSectionCompletedPage(taxYear),
    postCloseCompanyLoanSectionCompletedPage(taxYear)
  )
}
